[package]
name = "capdows_example"
version = "0.0.1"
edition = "2024"

[dependencies]
either = "1.14.0"

[dependencies.capdows]
path = "../capdows"

[dependencies.capdows_controls]
path = "../capdows_controls"

[build-dependencies]
embed-resource = "3.0.1"

