[package]
name = "capdows_example"
version = "0.0.1"
edition = "2021"

[dependencies]
either = "1.13.0"

[dependencies.capdows]
path = "../capdows"

[dependencies.capdows_controls]
path = "../capdows_controls"

[build-dependencies.capdows_resource]
path = "../capdows_resource"

