[package]
name = "capdows"
version = "0.0.1"
edition = "2021"

[dependencies]

[dependencies.windows]
version = "0.59.0"
features = [
    "Win32_System_LibraryLoader",
    "Win32_UI_Shell",
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Controls",
]
